### PR TITLE
add python 3.11 to workflows

### LINKED ISSUE #250: add python version 3.11 to the CI workflows
Python version 3.11 should be out on GitHub now, so it would be nice to add that to our workflows. Apparently 3.11 might come with quite some speedup compared to the previous versions.

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
# Description

In the call @lukashergt and I mentioned that we should probably add python3.11 to the workflows, given it is the latest version and neither of us have experienced issues testing with it locally.

Fixes #250 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

### CODE REVIEW

**Comment by AdamOrmondroyd** [comment]
Does codecov need editing to match these changes?

**Comment by lukashergt** [comment]
> Does codecov need editing to match these changes?

This is the usual problem when switching the python version used with codecov... 
@williamjameshandley, do you know how best to handle this? I usually end up force pushing these codecov changes...

**Comment by AdamOrmondroyd** [comment]
Not sure if @williamjameshandley did something behind the scenes but looks ready to go?

**Review by williamjameshandley — APPROVED** [review]
Now I have. I'll make the 3.11 ones compulsory after this is merged. Please squash and merge.

**Comment by lukashergt** [comment]
>> Not sure if @williamjameshandley did something behind the scenes but looks ready to go?
>
> Now I have. I'll make the 3.11 ones compulsory after this is merged. Please squash and merge.

@williamjameshandley, what _did_ you do behind the scenes?

**Comment by williamjameshandley** [comment]
branches > master > branch protections > _update branch protections_ > *save*

**Pull request merged**
