### PR TITLE
Limit to matplotlib<3.8.3

### PR DESCRIPTION
**Pull request by williamjameshandley**
# Description

Matplotlib 3.8.3 breaks anesthetic. Restricting to beneath this version until this is fixed.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [X] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [X] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

### CODE REVIEW

**Comment by AdamOrmondroyd** [comment]
Incredible 😢

**Comment by williamjameshandley** [comment]
Actually it's now less clear to me whether this is matplotlib 3.8.3, or python 3.12.

**Comment by AdamOrmondroyd** [comment]
I've been running almost exclusively on 3.12 locally since it released, so I would say probably not

**Comment by AdamOrmondroyd** [comment]
I've just run the test suite locally and no issues on my end, what were you seeing?

**Comment by williamjameshandley** [comment]
Ah -- is the `CI/latest-dependencies` breaking because of pandas 2.2.0, i.e. #359 ?

**Comment by AdamOrmondroyd** [comment]
yep

**Pull request closed without merging**
