### PR TITLE
Cast `root` to `str` to allow e.g. a `pathlib.Path` object to be used

### LINKED ISSUE #357: Allow `pathlib.Path` objects to be used as `root`
**Is your feature request related to a problem? Please describe.**
`pathlib.Path` provides a handy way of dealing with / vs \ on unix/dos-based OSs, but currently `anesthetic` cannot accept one as a `root` to `read_chains`. I also like how `/` is the append operator :) 

**Describe the solution you'd like**
I would like to be able to use `Path`s in this way, a well-placed cast to `str` should do the trick.

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
# Description

A quick one: I'm a fan of `pathlib.Path`, which takes care of / vs \ on unix/dos derived OSs, however, it cannot be used as the `read_chains` `root` argument since `+` is not defined for a `Path`, so I just cast it to string.

This PR puts the cast into `read_chains`. I have left all the other reading functions unmodified since they aren't intended to be invoked directly.

Fixes #357 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

### CODE REVIEW

**Review by williamjameshandley — APPROVED** [review]
This seems a pretty reasonable extension (version number and readme need bumping, but will re-approve

**Comment by AdamOrmondroyd** [comment]
will do once #356 is through

**Comment by AdamOrmondroyd** [comment]
Will be a nice opportunity to test that bump_version actually works on osx after #356 is merged

**Comment by appetrosyan** [comment]
I could test OS X compat

**Comment by AdamOrmondroyd** [comment]
If you like, but I'm also on Mac hence #356 in the first place

**Review by williamjameshandley — APPROVED** [review]

**Comment by AdamOrmondroyd** [comment]
> If you like, but I'm also on Mac hence #356 in the first place

Will was too fast 😢

**Comment by williamjameshandley** [comment]
Ah, apologies for stealing your fun! The bump version isn't much use in a merge resolution anyway. We'll have to wait until a new PR before trying #356 out on macOS

**Comment by AdamOrmondroyd** [comment]
dw I'll try it out on #359

**Pull request merged**
