### PR TITLE
Specify both pandas>=2.0.0 and matplotlib>=3.6.1 for conda CI

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
# Description

Conda is not always installing pandas>=2.0

Fixes # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [ ] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

### CODE REVIEW

**Comment by AdamOrmondroyd** [comment]
I think it might be the matplotlib version which causes issues (pandas 2 requires mpl 3.6.1, sometimes we get 3.2.2)

**Comment by AdamOrmondroyd** [comment]
When #295 was merged, the conda test which is now failing was installing mpl 3.7.1

**Review by lukashergt — APPROVED** [review]
> When #295 was merged, the conda test which is now failing was installing mpl 3.7.1

Did you mean #292 ?

But yes, for some obscure reason conda has started to sometimes choose to install an older matplotlib version... This should hopefully do it... Thanks @AdamOrmondroyd, please squash and merge.

**Comment by AdamOrmondroyd** [comment]
> Did you mean #292 ?

Yes (it was late here)

**Pull request merged**
