### PR TITLE
restrict pandas and matplotlib versions for conda CI

### LINKED ISSUE #368: Conda install ignores pandas version requirements
**Describe the bug**
Early this morning, conda updated to pandas 2.2.1. When #364 was merged, conda installed this version of pandas, despite the restriction in pyproject.toml to "pandas>=2.0.0,<2.2.0".

**To Reproduce**
Run the conda CI.

**Expected behavior**
An earlier, compatible version of pandas is installed by conda, and all tests pass

**Screenshots**
Screenshot 2024-03-05 at 12 12 24

**Additional context**

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #368 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

### CODE REVIEW

**Comment by AdamOrmondroyd** [comment]
Can't say I like this at all. @williamjameshandley @lukashergt is there a better way of enforcing conda to use the correct package versions?

**Comment by williamjameshandley** [comment]
NAFAIK. conda just works™

**Review by williamjameshandley — APPROVED** [review]
Many thanks @AdamOrmondroyd. LTGM

**Comment by AdamOrmondroyd** [comment]
> Many thanks @AdamOrmondroyd. LTGM

Looks to good me? 😆

**Pull request merged**
