### PR TITLE
Changes for pandas 2.0.0

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
# Description

Pandas2 has now released. Due to the large impact of #280, I have started #270 again here.

Some of these changes affect #235, so I have built on top of that here.

Changes:
- [x] implement `_PlanePlot2d._args_adjust()`
- [x] Remove `HistPlot._makeplot()`, copied from pandas #48888 (which is already outdated)
- [x] remove `mad`, this has been taken out of pandas
- [x] require matplotlib>=3.6.1
- [x] The Gelman-Rubin statistic is broken, as the `groupby()` seems to cause the pandas kwargs to `cov()`to be passed to our `cov()`, which raises the `NotImplementedError` - need to see how this fits in with #272
- [x] adjust_docstrings() is broken
- [x] update pandas requirement to ~= 2.0.0 once it actually releases
- [ ] wait for conda to catch up
- [ ] easier to wait for #280 to merge first

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py - I think this is worthy of a minor increment

### CODE REVIEW

**Comment by AdamOrmondroyd** [comment]
Still waiting for conda to catch up

**Comment by williamjameshandley** [comment]
Now that we've closed #280, is there anything left to do for this?

**Comment by williamjameshandley** [comment]
Do pandas 2.0.0 updates need to be implemented for an anesthetic 2.0.0 release?

**Comment by AdamOrmondroyd** [comment]
> Now that we've closed #280, is there anything left to do for this?

This builds on #280, so I'll have to do it again

**Comment by williamjameshandley** [comment]
Let me know if there's anything I can do to help -- apologies for messing things around. Is #270 recoverable?

**Pull request closed without merging**
